// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }









import Head from 'next/head'
// import clientPromise from '../lib/mongodb'
import { InferGetServerSidePropsType } from 'next'

import { Grid, Img } from "@chakra-ui/react";
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Homepage from '../components/Homepage/Homepage';
import axios from 'axios';


// export async function getServerSideProps(context) {
//   try {
//     await clientPromise
//     // `await clientPromise` will use the default database passed in the MONGODB_URI
//     // However you can use another database (e.g. myDatabase) by replacing the `await clientPromise` with the following code:
//     //
//     // `const client = await clientPromise`
//     // `const db = client.db("myDatabase")`
//     //
//     // Then you can execute queries against your database like so:
//     // db.find({}) or any of the MongoDB Node Driver commands

//     return {
//       props: { isConnected: true },
//     }
//   } catch (e) {
//     console.error(e)
//     return {
//       props: { isConnected: false },
//     }
//   }
// }

export default function Home({props}) {
  return (
    <div className="container">
      <Navbar />
      <Homepage/>
      <Footer />
    </div>
  )
}

// export async function getServerSideProps({req}: any){
//   console.log('SERVER SIDE ', req.cookies)
//   // let {token} = JSON.parse(req.cookies.mohollamartJwt);
//   let {token} = JSON.parse(req.cookies.mohallaMartJwt);
//     let resp = await axios.get("http://localhost:3000/api/users/details", {headers: {token}})
//     if(resp.data.ack===false){
//       let {token, refreshToken} = JSON.parse(req.cookies.mohallaMartJwt);
//       console.log(refreshToken)
//       resp = await axios.get("http://localhost:3000/api/users/refresh", {headers: {"token": refreshToken}})
//       if(resp.data.ack){
//         let {token} = JSON.parse(req.cookies.mohallaMartJwt);
//         resp = await axios.get("http://localhost:3000/api/users/details", {headers: {token}})
//       }
//     }
//     let data = resp.data;
//     console.log(data)
//   return {
//       props: {props: data}
//   }
// }
